modLoader = "javafml"
loaderVersion = "[${required_forge_loader_version},)"
issueTrackerURL = "https://github.com/Armourers-Workshop/Armourers-Workshop/issues"
displayURL = "https://github.com/Armourers-Workshop/Armourers-Workshop"
logoFile = "icon.png"
license = "CC-BY-NC-SA-3.0"

[[mods]]
modId = "armourers_workshop"
version = "${version}"
displayName = "Armourer's Workshop"
authors = "RiskyKen, SAGESSE"
description = '''
Minecraft armour customization mod.
'''

[[dependencies.armourers_workshop]]
modId = "forge"
mandatory = true
versionRange = "[${required_forge_api_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armourers_workshop]]
modId = "minecraft"
mandatory = true
versionRange = "[${required_minecraft_version},)"
ordering = "NONE"
side = "BOTH"