plugins {
    id "base"
    id "java"
    id "cocoon-loom" version "1.4.0"
}

cocoon {
    minecraft = project.minecraft_api_version
    mappings = "official"
}

subprojects {
    apply plugin: "cocoon-loom"

    sourceSets.forEach {
        it.java.srcDirs "../versions/${project.minecraft_version}/${project.name}/src/${it.name}/java"
        it.resources.srcDirs "../versions/${project.minecraft_version}/${project.name}/src/${it.name}/resources"
        it.java.srcDirs "../versions/library/${project.name}/src/${it.name}/java"
        it.resources.srcDirs "../versions/library/${project.name}/src/${it.name}/resources"
        it.java.srcDirs "../versions/gametest/${project.name}/src/${it.name}/java"
        it.resources.srcDirs "../versions/gametest/${project.name}/src/${it.name}/resources"
    }

    dependencies {
        compileOnly "org.checkerframework:checker-qual:3.49.5"
        testCompileOnly "org.checkerframework:checker-qual:3.49.5"
        compileOnly "com.google.code.findbugs:jsr305:3.0.2"
        testCompileOnly "com.google.code.findbugs:jsr305:3.0.2"
    }

    signJar {
        alias = System.getenv("AW_SIGN_ALIAS")
        keyPass = System.getenv("AW_SIGN_KEY_PASS")
        keyStore = System.getenv("AW_SIGN_STORE")
        keyStorePass = System.getenv("AW_SIGN_STORE_PASS")
    }

    jabel {
        api = "com.xpdustry:jabel"
        version = "1.1.0"
        compilerArgs << "-Xmx2048M"
        // we only enable jabel for minecraft 1.16.x
        onlyIf {
            cocoon.minecraftNumber < 180000
        }
    }
}

allprojects {
    apply plugin: "java-library"
    apply plugin: "maven-publish"

    def uname = project.archives_base_name.toLowerCase()
    def release = project.java_version as int

    group = project.maven_group

    if (version == "unspecified") {
        version = "2.0.0-homebaked"
    }

    base {
        archivesName = "${uname}-${project.name}-${project.minecraft_api_version}"
    }

    repositories {
        // Add repositories to retrieve artifacts from in here.
        // You should only use this when depending on other mods because
        // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
        // See https://docs.gradle.org/current/userguide/declaring_repositories.html
        // for more information about repositories.
        mavenLocal()
        maven { url "https://maven.neoforged.net/releases/" }
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "https://maven.blamejared.com/" }
        maven { url "https://maven.xpdustry.com/releases/" }
        // Third party mods repositories.
        maven {
            url "https://api.modrinth.com/maven/"
            content {
                includeGroup "maven.modrinth"
            }
        }
        maven {
            url "https://cursemaven.com/"
            content {
                includeGroup "curse.maven"
            }
        }
    }

    dependencies {
        compileOnly "systems.manifold:manifold-ext:${project.manifold_version}"
        annotationProcessor "systems.manifold:manifold-ext:${project.manifold_version}"
        testCompileOnly "systems.manifold:manifold-ext:${project.manifold_version}"
        testAnnotationProcessor "systems.manifold:manifold-ext:${project.manifold_version}"
    }

    java {
        withSourcesJar()
    }

    tasks.withType(Test).configureEach {
        failOnNoDiscoveredTests = false
    }

    tasks.withType(JavaCompile).configureEach {
        options.release = release
        options.encoding = "UTF-8"
        options.compilerArgs << "-Xplugin:Manifold no-bootstrap"
    }
}
