loom.platform=fabric
permissions_api_version=me.lucko:fabric-permissions-api:0.3.1
trinkets_api_version=maven.modrinth:trinkets:OLwsMJv4
accessories_api_version=
mrcrayfishbackpack_api_version=curse.maven:backpacked-667380:4728984
travelersbackpack_api_version=maven.modrinth:travelersbackpack:3nZgdUsQ
sophisticatedbackpack_api_version=maven.modrinth:sophisticated-backpacks-(unoffical-fabric-port):xDzV8ICU
ryoamiclights_api_version=maven.modrinth:ryoamiclights:pu9jKeK9
lambdynamiclights_api_version=maven.modrinth:lambdynamiclights:YQkZSlfq
sodiumdynamiclights_api_version=
