# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
loaderVersion="[36,)"
#updateJSONURL=""
issueTrackerURL="https://github.com/RiskyKen/Armourers-Workshop/issues"
displayURL="https://github.com/RiskyKen/Armourers-Workshop"
logoFile="logo.png"
license="All rights reserved"

[[mods]]
	modId="armourers_workshop"
    version="${version}"
    authors="RiskyKen, SAGESSE"
	displayName="Armourer's Workshop"
	description="Minecraft armour customization mod."

[[dependencies.armourers_workshop]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies.armourers_workshop]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version}"
    ordering="NONE"
    side="BOTH"
