loom.platform=forge
epicfight_api_version=maven.modrinth:epic-fight:6SuH0tnY
curios_api_version=maven.modrinth:curios:sVuCrC2E
tacz_api_version=maven.modrinth:timeless-and-classics-zero:NCwx3a6P
mrcrayfishbackpack_api_version=curse.maven:backpacked-352835:4725663
travelersbackpack_api_version=maven.modrinth:travelersbackpack:voGeNbOd
sophisticatedbackpack_api_version=maven.modrinth:sophisticated-backpacks:ySJuJiG9
ryoamiclights_api_version=maven.modrinth:ryoamiclights:KIUKMIXH
lambdynamiclights_api_version=curse.maven:dynamiclights-reforged-551736:3817266
sodiumdynamiclights_api_version=
