loom.platform=fabric
permissions_api_version=me.lucko:fabric-permissions-api:0.3.1
trinkets_api_version=maven.modrinth:trinkets:JagCscwi
accessories_api_version=maven.modrinth:accessories:uPPIhLTH
mrcrayfishbackpack_api_version=curse.maven:backpacked-352835:5852971
travelersbackpack_api_version=maven.modrinth:travelersbackpack:qerauDs0
sophisticatedbackpack_api_version=maven.modrinth:sophisticated-backpacks-(unoffical-fabric-port):x3HvtfXu
ryoamiclights_api_version=maven.modrinth:ryoamiclights:eFFsHtIr
lambdynamiclights_api_version=
sodiumdynamiclights_api_version=maven.modrinth:sodium-dynamic-lights:BsbJhy7W
