trinkets_api_version=maven.modrinth:trinkets:JagCscwi
permissions_api_version=me.lucko:fabric-permissions-api:0.4.0
mrcrayfishbackpack_api_version=curse.maven:backpacked-352835:5852971
travelersbackpack_api_version=maven.modrinth:travelersbackpack:DRssSA0N
sophisticatedbackpack_api_version=maven.modrinth:sophisticated-backpacks-(unoffical-fabric-port):x3HvtfXu
ryoamicLights_api_version=maven.modrinth:ryoamiclights:eFFsHtIr
lambdynamiclights_api_version=maven.modrinth:sodium-dynamic-lights:BsbJhy7W
