loom.platform=neoforge
epicfight_api_version=maven.modrinth:epic-fight:AMdbNVsB
curios_api_version=maven.modrinth:curios:QBtodtmR
accessories_api_version=maven.modrinth:accessories:CtRim6mz
tacz_api_version=maven.modrinth:timeless-and-classics-zero:Qd1RlJ8k
travelersbackpack_api_version=maven.modrinth:travelersbackpack:a3VUPlc1
mrcrayfishbackpack_api_version=curse.maven:backpacked-352835:5852973
sophisticatedbackpack_api_version=maven.modrinth:sophisticated-backpacks:q4YzYKAb
ryoamiclights_api_version=maven.modrinth:ryoamiclights:c2Th4NIB
lambdynamiclights_api_version=
sodiumdynamiclights_api_version=maven.modrinth:sodium-dynamic-lights:XI0WLXdn