loom.platform=neoforge
jei_api_version=maven.modrinth:jei:TxS03dKM
epicfight_api_version=maven.modrinth:epic-fight:AMdbNVsB
curios_api_version=maven.modrinth:curios:QBtodtmR
tacz_api_version=maven.modrinth:timeless-and-classics-zero:Qd1RlJ8k
mrcrayfishbackpack_api_version=curse.maven:backpacked-352835:5852973
travelersbackpack_api_version=maven.modrinth:travelersbackpack:a3VUPlc1
sophisticatedbackpack_api_version=maven.modrinth:sophisticated-backpacks:q4YzYKAb
ryoamiclights_api_version=maven.modrinth:ryoamiclights:c2Th4NIB
lambdynamiclights_api_version=
sodiumdynamiclights_api_version=maven.modrinth:sodium-dynamic-lights:XI0WLXdn
