package moe.plushie.armourers_workshop.core.client.other;

public enum SkinVertexFormat {

    LINE,
    LINE_STRIP,

    IMAGE,

    BLIT_MASK,

    GUI_IMAGE,
    GUI_COLOR,
    GUI_HIGHLIGHTED_TEXT,

    BLOCK,
    BLOCK_CUTOUT,

    ENTITY_CUTOUT,
    ENTITY_CUTOUT_NO_CULL,
    ENTITY_TRANSLUCENT,
    ENTITY_ALPHA,

    SKIN_BLOCK_FACE_SOLID,
    SKIN_BLOCK_FACE_LIGHTING,
    SKIN_BLOCK_FACE_LIGHTING_TRANSLUCENT,
    SKIN_BLOCK_FACE_TRANSLUCENT,

    SKIN_CUBE_FACE,
    SKIN_CUBE_FACE_LIGHTING,

    SKIN_MESH_FACE,
    SKIN_MESH_FACE_LIGHTING,
}
