package moe.plushie.armourers_workshop.core.client.other;

public enum SkinVertexFormat {

    LINE,
    LINE_STRIP,

    BLIT_MASK,
    BLIT_TEXTURED,

    GUI_COLOR,
    GUI_TEXTURED,

    BLOCK,
    BLOCK_CUTOUT,

    ENTITY_CUTOUT,
    ENTITY_CUTOUT_NO_CULL,
    ENTITY_TRANSLUCENT,
    ENTITY_ALPHA,

    SKIN_PARTICLE_CUTOUT,
    SKIN_PARTICLE_CUTOUT_EMISSIVE,

    SKIN_BLOCK_FACE_SOLID,
    SKIN_BLOCK_FACE_EMISSIVE,
    SKIN_BLOCK_FACE_TRANSLUCENT_EMISSIVE,
    SKIN_BLOCK_FACE_TRANSLUCENT,

    SKIN_CUBE_FACE_SOLID,
    SKIN_CUBE_FACE_EMISSIVE,
    SKIN_CUBE_FACE_TRANSLUCENT_EMISSIVE,
    SKIN_CUBE_FACE_TRANSLUCENT,

    SKIN_MESH_FACE_SOLID,
    SKIN_MESH_FACE_EMISSIVE,
    SKIN_MESH_FACE_TRANSLUCENT_EMISSIVE,
    SKIN_MESH_FACE_TRANSLUCENT,
}
