loom.platform=forge
jei_api_version=maven.modrinth:jei:92yH4H3m
epicfight_api_version=maven.modrinth:epic-fight:qbWaFntW
curios_api_version=maven.modrinth:curios:5qPuCFYD
tacz_api_version=
mrcrayfishbackpack_api_version=curse.maven:backpacked-352835:4725662
travelersbackpack_api_version=maven.modrinth:travelersbackpack:6NAEVL5U
sophisticatedbackpack_api_version=maven.modrinth:sophisticated-backpacks:aplfC9U1
ryoamicLights_api_version=maven.modrinth:ryoamiclights:PJHSvVOR
lambdynamiclights_api_version=curse.maven:dynamiclights-reforged-551736:3574974
