loom.platform=forge
epicfight_api_version=maven.modrinth:epic-fight:8fBU4NVv
curios_api_version=maven.modrinth:curios:QBtodtmR
accessories_api_version=maven.modrinth:accessories:ALKwAjwA
tacz_api_version=maven.modrinth:timeless-and-classics-zero:Qd1RlJ8k
mrcrayfishbackpack_api_version=curse.maven:backpacked-352835:5813547
travelersbackpack_api_version=maven.modrinth:travelersbackpack:PpjFxlyX
sophisticatedbackpack_api_version=maven.modrinth:sophisticated-backpacks:zkb0vOdU
ryoamiclights_api_version=maven.modrinth:ryoamiclights:c2Th4NIB
lambdynamiclights_api_version=
sodiumdynamiclights_api_version=maven.modrinth:sodium-dynamic-lights:I156ee3A
