trinkets_api_version=maven.modrinth:trinkets:XqLNMi9J
mrcrayfishbackpack_api_version=
travelersbackpack_api_version=maven.modrinth:travelersbackpack:eWGV5ntd
sophisticatedbackpack_api_version=
ryoamicLights_api_version=maven.modrinth:ryoamiclights:EdjwaXwJ
lambdynamiclights_api_version=maven.modrinth:lambdynamiclights:zhBXhMhZ
