plugins {
}

cocoon {
    common {
        api = project.fabric_api_version
        loader = project.fabric_loader_version
        accessWidenerPath = file("src/main/resources/armourersworkshop.accesswidener")
    }
}

dependencies {
    testImplementation "org.junit.jupiter:junit-jupiter:5.10.0"
    testImplementation "org.junit.platform:junit-platform-engine:1.10.2"
    testImplementation "org.junit.platform:junit-platform-launcher:1.10.2"
}

jar {
    manifest {
        // for manifold to recognize extensions, as a performance measure,
        // the library must declare it has extensions to process.
        // do that using the Contains-Sources manifest entry.
        attributes("Contains-Sources": "java,class")
    }
}
