trinkets_api_version=curse.maven:trinkets-341284:3100959
permissions_api_version=me.lucko:fabric-permissions-api:0.3.1
mrcrayfishbackpack_api_version=
travelersbackpack_api_version=maven.modrinth:travelersbackpack:SeUbJGkP
sophisticatedbackpack_api_version=
ryoamiclights_api_version=maven.modrinth:ryoamiclights:qGKe5QHU
lambdynamiclights_api_version=maven.modrinth:lambdynamiclights:hKXQNf9z
sodiumdynamiclights_api_version=