trinkets_api_version=maven.modrinth:trinkets:AHxQGtuC
mrcrayfishbackpack_api_version=curse.maven:backpacked-352835:5813545
travelersbackpack_api_version=maven.modrinth:travelersbackpack:PaHAEoCa
sophisticatedbackpack_api_version=maven.modrinth:sophisticated-backpacks-(unoffical-fabric-port):QohWxuZ4
ryoamicLights_api_version=maven.modrinth:ryoamiclights:VTzHz71U
lambdynamiclights_api_version=maven.modrinth:sodium-dynamic-lights:EYnKyLWV
