trinkets_api_version=maven.modrinth:trinkets:AHxQGtuC
permissions_api_version=me.lucko:fabric-permissions-api:0.3.1
mrcrayfishbackpack_api_version=curse.maven:backpacked-352835:5813545
travelersbackpack_api_version=maven.modrinth:travelersbackpack:PaHAEoCa
sophisticatedbackpack_api_version=maven.modrinth:sophisticated-backpacks-(unoffical-fabric-port):QohWxuZ4
ryoamiclights_api_version=maven.modrinth:ryoamiclights:VTzHz71U
lambdynamiclights_api_version=
sodiumdynamiclights_api_version=maven.modrinth:sodium-dynamic-lights:EYnKyLWV
