name: Release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ '16.5', '18.2', '19.2', '20.1', '21.1', '26.1' ]

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup environment
        id: setup-env
        run: ./scripts/setup.sh "${{ github.event.release.tag_name }}" "${{ matrix.version }}" >> "$GITHUB_OUTPUT"

      - name: Setup cache
        uses: actions/cache/restore@v5
        with:
          key: ${{ steps.setup-env.outputs.cache_key }}
          path: ${{ steps.setup-env.outputs.cache_path }}

      - name: Clean test resources
        run: rm -rf "versions/gametest"

      - name: Switch to ${{ matrix.version }}
        run: ./gradlew -Pversion="${{ steps.setup-env.outputs.version }}" -p "versions/${{ matrix.version }}"

      - name: Build Project
        run: ./gradlew -Pversion="${{ steps.setup-env.outputs.version }}" build
        env:
          AW_SIGN_ALIAS: ${{ secrets.AW_SIGN_ALIAS }}
          AW_SIGN_KEY_PASS: ${{ secrets.AW_SIGN_KEY_PASS }}
          AW_SIGN_STORE: ${{ secrets.AW_SIGN_STORE }}
          AW_SIGN_STORE_PASS: ${{ secrets.AW_SIGN_STORE_PASS }}

      - name: Upload Fabric Files
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: ${{ steps.setup-env.outputs.fabric_archives_name }}
          version: ${{ steps.setup-env.outputs.fabric_archives_version }}
          version-type: beta
          #version-type: release

          files: fabric/build/libs/${{ steps.setup-env.outputs.fabric_archives_name }}.jar
          loaders: ${{ steps.setup-env.outputs.fabric_archives_loader }}

          game-versions: ${{ steps.setup-env.outputs.game_version }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          modrinth-id: y4JF3gXL
          modrinth-token: ${{ secrets.AW_MODRINTH_TOKEN }}

          curseforge-id: 229523
          curseforge-token: ${{ secrets.AW_CURSEFORGE_TOKEN }}

          retry-attempts: 6
          retry-delay: 30000
          fail-mode: warn

      - name: Upload Forge Files
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: ${{ steps.setup-env.outputs.forge_archives_name }}
          version: ${{ steps.setup-env.outputs.forge_archives_version }}
          version-type: beta
          #version-type: release

          files: forge/build/libs/${{ steps.setup-env.outputs.forge_archives_name }}.jar
          loaders: ${{ steps.setup-env.outputs.forge_archives_loader }}

          game-versions: ${{ steps.setup-env.outputs.game_version }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          modrinth-id: y4JF3gXL
          modrinth-token: ${{ secrets.AW_MODRINTH_TOKEN }}

          curseforge-id: 229523
          curseforge-token: ${{ secrets.AW_CURSEFORGE_TOKEN }}

          retry-attempts: 6
          retry-delay: 30000
          fail-mode: warn
