name: Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    needs: init
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [ '16.5', '18.2', '19.2', '20.1', '21.1', '26.1' ]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup environment
        id: setup-env
        run: ./scripts/setup.sh "${{ github.sha }}" "${{ matrix.version }}" >> "$GITHUB_OUTPUT"

      - name: Setup cache
        uses: actions/cache/restore@v4
        with:
          key: ${{ steps.setup-env.outputs.cache_key }}
          path: ${{ steps.setup-env.outputs.cache_path }}

      - name: Switch to ${{ matrix.version }}
        run: ./gradlew -Pversion=${{ steps.setup-env.outputs.release_version }} -p "versions/${{ matrix.version }}"

      - name: Build Project
        run: ./gradlew -Pversion=${{ steps.setup-env.outputs.release_version }} build

      # this is a bug in the java 25 bug, it can be removed java 27 is released.
      - uses: actions/setup-java@v4
        if: ${{ matrix.version == '16.5' }}
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run server test
        run: ./gradlew -Pversion=${{ steps.setup-env.outputs.release_version }} runServerTest

  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup environment
        id: setup-env
        run: ./scripts/setup.sh >> "$GITHUB_OUTPUT"

      - name: Setup cache
        id: setup-cache
        uses: actions/cache@v4
        with:
          key: ${{ steps.setup-env.outputs.cache_key }}
          path: ${{ steps.setup-env.outputs.cache_path }}
          lookup-only: true

      - name: Generate cache
        if: ${{ steps.setup-cache.outputs.cache-hit != 'true' }}
        run: ./scripts/generate.sh
